### PR TITLE
Ps45 get user test

### PR DESCRIPTION
**Pull request by mvstoyan**
He, @akosasante 
I'm facing issues with the commit based on the tutorial you shared. I'm encountering errors related to expected HTTP response codes. In one test, it's expecting a 200 code, but I'm getting 401. In another test, it expects a 404 code, but I'm getting 401.

Additionally, I tried to implement token verification(ec8cd06), and the test indicated success. However, I'm currently stuck at this point in the tutorial and unsure about the next steps. I would appreciate your help.

### CODE REVIEW

**Comment by akosasante** [comment]
`401` sounds like an auth error.

Looking at `userRoutes` I see that the `getSingleUser` route is protected by `authenticateUser` middleware. I had missed that in my instructions 🙈 

Generally, we want our tests to follow the same behaviour and actions as a user using our application would. So in order to use/test this endpoint we need to have a logged-in/authenticated request that has cookies on it. 

1. First create a user in the test database with an admin role:

```js
let adminUser;
beforeAll(async () => {
  mongodb = await MongoMemoryServer.create();
  const url = mongodb.getUri();
  process.env.MONGO_URL = url;
  mongooseConnection = await connectDB(url);
  server = await app.listen(8001);

 adminUser = await User.create({
    name: "John Doe",
    email: "joe@example.com.com",
    password: "testing",
    role: "admin"
  });
});
```

2. Create a function that we can reuse throughout the tests that will log in and give us the cookies

```js
// log in to the API, grab the signed cookie from the response headers
const loginAndReturnCookie = async (credentials) => {
  const resp = await request(app)
    .post('/api/v1/auth/login')
    .send(credentials);

  const cookieHeader = resp.headers['set-cookie'];
  const signedCookie = cookieHeader.find(cookie => cookie.startsWith('token')).split(';')[0];
  return signedCookie;
}
```

3. In the "Arrange" step, log in and get the cookie:

```js
// Arrange
    const signedCookie = await login({email: adminUser.email, password: adminUser.password})
```

4. In the "Act" step, set the cookie as a header in the request made to the "get single user" endpoint

```js
    // Act
    const response = await request(app).get(`/api/v1/users/${user.id}`).set('Cookie', signedCookie);
```

Same idea for the 'not found' test:

```js
    // Arrange
    const signedCookie = await login({email: "aasante@gmail.com", password: "testing"})

    // Act
    const response = await request(app).get('/api/v1/users/nonexistentUserId').set('Cookie', signedCookie);
```

**Comment by mvstoyan** [comment]
Made the necessary updates to the code based on your guidance. The tests are now passing as expected.
I hope I haven't missed anything.

**Review by akosasante — APPROVED** [review]
LGTM :+1: :rocket:

**Comment by mvstoyan** [comment]
Thank you @akosasante, for all your help!

**Pull request merged**
